version: 2.1

orbs:
  node: circleci/node@3.0.1
  heroku: circleci/heroku@1.0.1
  
  services:
    type: boolean
    default: true
  web-ui:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  build:
    executor: node

    steps:
      - checkout

      - run:
          working_directory: services
          name: install dependencies
          command: |
            npm install
      - run:
          working_directory: services
          name: Running npm test
          command: |
            npm run test
      - setup_remote_docker:
          version: 18.09.3
      - run:
          working_directory: services
          name: Build Docker image
          command: |
            docker build -t ostromecky-employees-api:circleci .
      # - persist_to_workspace:
      #     root: ~/project
      #     paths:
      #       - services

  deploy:
    machine: true

    steps:
      - checkout

      - run:
          name: Pushing to heroku registry
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            heroku container:login
            heroku container:push -a ostromecky-employees-api --arg NODE_ENV=production web
            heroku container:release -a ostromecky-employees-api web

workflows:
  version: 2

  services:
    jobs:
      - build:
          name: services-build
      - deploy:
          name: services-deploy
        
          requires:
            - services-build
