version: 2.1

orbs:
  node: circleci/node@3.0.1
  heroku: circleci/heroku@1.0.1

  
  services:
    type: boolean
    default: true
  web-ui:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  build:
    executor: node

    steps:
      - checkout
      # This step is added only to show that we are in the package directory

      - run:
          working_directory: services
          name: install dependencies
          command: |
            npm install
      - run:
          working_directory: services
          name: Running npm test
          command: |
            npm run test
      - setup_remote_docker:
          version: 18.09.3
      - run:
          working_directory: services
          name: Build Docker image
          command: |
            docker build -t ostromecky-employees-api:circleci .
            docker images
      - persist_to_workspace:
          root: ~/project
          paths:
            - services

  deploy:
    executor: node
    working_directory: services

    steps:
      - heroku/install
      - run:
          name: Pushing to heroku registry
          command: |
            heroku container:login
            heroku container:push web --arg NODE_ENV=production -a ostromecky-employees-api
            heroku container:release web -a ostromecky-employees-api

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  # Workflows defined for each package.

  services:
    jobs:
      - build:
          name: services-build
      - deploy:
          name: services-deploy
        
          requires:
            - services-build
  # web-ui:
  #   jobs:
  #     - build:
  #         name: web-ui-build
  #         package_name: web-ui
  #         filters:
  #           branches:
  #             only:
  #               - master
  #     - deploy:
  #         name: app-deploy
  #         package_name: web-ui
  #         requires:
  #           - Web-ui-build
  #         filters:
  #           branches:
  #             only:
  #               - master
