version: '3.7'
services:
  app:
    build:
      context: .
      target: development
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
    ports:
      - '3000:3000'
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_SCHEMA}

  pgadmin:
    image: dpage/pgadmin4
    links:
      - 'postgres:pg'
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: qwer!234
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
  app:
